version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    depends_on:
      - server
    ports:
    - 5279:5173
    links:
    - 'server'
  server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: your_gpu_count
              capabilities: [gpu]
    ports:
    - 5278:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
