# syntax=docker/dockerfile:1

FROM nvidia/cuda:12.3.1-base-ubuntu20.04


WORKDIR /app

# RUN rm /etc/apt/sources.list.d/cuda.list
RUN apt update -y && apt install curl -y
RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt install -y python3.10
RUN apt install python3.10-distutils -y
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10


ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

RUN mkdir -p /deployment_assets/pkgs

# Copy the source code into the container.
COPY ./deployment_assets/pkgs/requirements.txt /deployment_assets/pkgs/
RUN python3.10 -m pip install -r /deployment_assets/pkgs/requirements.txt


COPY --chown=appuser . .


# # Expose the port that the application listens on.
EXPOSE 8000
HEALTHCHECK --interval=600s --timeout=40s --start-period=5s --retries=4 CMD curl --fail http://127.0.0.1:8000/health_check/get_health || exit 1


# # Run the application.
CMD uvicorn main:app --reload --host 0.0.0.0

# ENTRYPOINT ["tail", "-f", "/dev/null"]